### ISSUE TITLE
O_VALUE

### ISSUE THREAD

**Issue by ikechan8370** [reko-beep/hsr-data#10]
Hi, this project is awesome and useful. Recently I have used master branch to download raw_data, but the data seems to become inaccurate these days (hash of some images became 404). After changing O_VALUE to "e2f24f9ed0117cf0db2e1ecf375f7e6a", the problems solved. Maybe the O_VALUE should be changed regularly?

**Comment by Vocaloid2048** [comment]
Sorry for asking a dummy question, is that there have any possible way to get `O_VALUE` by user/myself? It seems `O_VALUE` has changed again ...
