### ISSUE TITLE
Are you willing to update the image content to version 1.3?

### ISSUE THREAD

**Issue by HyBoxwood** [reko-beep/hsr-data#14]
I have some issues with my network and cannot access starrailstation.com, but I really want the portrait of Dan Heng Yinyue! Thank you!

**Comment by reko-beep** [comment]
sorry for late response, it only needed `O_VALUE` of v13.0
I updated it. Pretty sure, it will work as intended.

**Comment by HyBoxwood** [comment]
I changed 'LiteralString' to 'Literal' in 'main.py', so I was able to run 'raw_data.py' and got a 'raw_data' folder. I read in the 'readme.md' that 'ascension.py' still can't be used, so how can I get the images? I'm sorry, I'm not very tech-savvy.
