### ISSUE TITLE
A little bit issues on ./hsr_client/backend/srs_backend/__init__.py

### ISSUE THREAD

**Issue by Vocaloid2048** [reko-beep/hsr-data#4]
Sorry for holding an issue agan ... 
After my silly testing on running raw_data.py (branch "master")
I've found that there have two little mistakes : 

Row 014 : import **datamodels** as models >>> I guess u mean **hsr_client.datamodels**
Row 101 :     def get_all_items(self,  type: Types = None, language: Languages = Languages.**ENG**) -> list[SearchItem]:  >>> According to the constants.py in ./hsr_client , it should be **EN** instead of **ENG**

Finally, thx for your hard work and notice!
- Voc

**Comment by BobyClaws** [comment]
you'll find even more silly things, ;) we need to organize who works on what, and let others know that. hopefully things like this don't happen often
